name: test

on: [push]

# Cancel previous builds by only allowing one concurrent build per ref.
concurrency:
  group: die-ringe-app-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4

      - name: Detect Flutter version
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: Analyze
        run: flutter analyze --fatal-infos

      - name: Get Packages
        run: flutter pub get

      - name: Test
        run: flutter test --coverage --reporter expanded
